Добавил новый пайплан и docker-compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -39,7 +39,48 @@ services:
       KEY: ${KEY}
       LOGIN: ${LOGIN}         # просто прокидываем, чтобы при запуске через github в allure отображались
       PASSWORD: ${PASSWORD}
-      ALLURE_TESTOPS_URL: ${ALLURE_TESTOPS_URL}   # Три переменные ниже передаем для Allure Test Ops
+      ALLURE_TESTOPS_URL: ${ALLURE_TESTOPS_URL}   # Пять переменных ниже передаем для Allure Test Ops
+      ALLURE_PROJECT_ID: ${ALLURE_PROJECT_ID}
+      ALLURE_API_KEY: ${ALLURE_API_KEY}
+      ALLURE_JOB_UID: ${ALLURE_JOB_UID}
+      ALLURE_JOB_RUN_UID: ${ALLURE_JOB_RUN_UID}
+    tty: true
+
+  pom_dz_allure:
+    image: pom_dz:v1
+    build:
+      context: .
+      dockerfile: Dockerfile
+    volumes:
+      - ./:/usr/workspace
+      - /dev/shm:/dev/shm
+    command: |
+      curl -fsSL https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl &&
+      chmod +x allurectl &&
+     
+      if [[ ! -f allurectl ]]; then
+        echo "Failed to download allurectl binary."
+        exit 1
+      fi &&
+      
+      /bin/sh -c 'echo "STAGE=$STAGE BROWSER=$BROWSER MARKER=$MARKER KEY=$KEY \
+      ALLURE_TESTOPS_URL=$ALLURE_TESTOPS_URL ALLURE_PROJECT_ID=$ALLURE_PROJECT_ID ALLURE_API_KEY=$ALLURE_API_KEY"; \
+      pytest -sv $${KEY:+-k "$$KEY"} $${MARKER:+-m "$$MARKER"} -o log_cli=true --alluredir=allure-results' &&
+      ./allurectl upload \
+          --endpoint=$ALLURE_TESTOPS_URL \
+          --project-id=$ALLURE_PROJECT_ID \
+          --token=$ALLURE_API_KEY \
+          "./allure-results"      
+
+    shm_size: 2gb
+    environment:
+      STAGE: ${STAGE:-release}
+      BROWSER: ${BROWSER:-chrome}
+      MARKER: ${MARKER}
+      KEY: ${KEY}
+      LOGIN: ${LOGIN}
+      PASSWORD: ${PASSWORD}
+      ALLURE_TESTOPS_URL: ${ALLURE_TESTOPS_URL}   # Пять переменных ниже передаем для Allure Test Ops
       ALLURE_PROJECT_ID: ${ALLURE_PROJECT_ID}
       ALLURE_API_KEY: ${ALLURE_API_KEY}
       ALLURE_JOB_UID: ${ALLURE_JOB_UID}
