Еще раз через compose

diff --git a/.github/workflows/tests_allure_test_ops.yml b/.github/workflows/tests_allure_test_ops.yml
--- a/.github/workflows/tests_allure_test_ops.yml
+++ b/.github/workflows/tests_allure_test_ops.yml
@@ -105,21 +105,24 @@ jobs:
 #        какой-то как будто кривой ссылкой, но может и ошибаюсь в причине. И тесты не запускались из Allure TestOps, на job, который создавался автоматом была ошибка
 #        соединения, а на job, который создал руками было зеленое соединение, но не видел тесты, может проблема в бесплатной версии ??? В данном пайплане Шаг 6 для
 #        передачи отчета в Allure TestOps, и много переменных, начинающихся на ALLURE
-#      - name: Send results to Allure TestOps using allurectl
-#        run: |
-#          curl -fsSL https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl
-#          chmod +x allurectl
-#
-#          if [[ ! -f allurectl ]]; then
-#            echo "Failed to download allurectl binary."
-#            exit 1
-#          fi
-#
-#          ./allurectl upload \
-#          --endpoint="${{ secrets.ALLURE_TESTOPS_URL }}" \
-#          --project-id="${{ secrets.ALLURE_PROJECT_ID }}" \
-#          --token="${{ secrets.ALLURE_API_KEY }}" \
-#          "./allure-results"
+      - name: Send results to Allure TestOps using allurectl
+        run: |
+          curl -fsSL https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl
+          chmod +x allurectl
+
+          if [[ ! -f allurectl ]]; then
+            echo "Failed to download allurectl binary."
+            exit 1
+          fi
+
+          ./allurectl upload \
+          --endpoint="${{ secrets.ALLURE_TESTOPS_URL }}" \
+          --project-id="${{ secrets.ALLURE_PROJECT_ID }}" \
+          --token="${{ secrets.ALLURE_API_KEY }}" \
+          -job-name="${{ github.job }}" \
+          --job-run-uid="${{ github.run_id }}" \
+          --job-uid="${{ github.run_number }}" \
+          "./allure-results"
 
       # Шаг 7 - Деплой на gh-pages, спецальная гитхабовская джоба просто заполняем вот так, заливаем allure-report на ветку gh-pages
       - name: Deploy to Github Pages
