Удалил папйплан

diff --git a/.github/workflows/tests_allure_test_ops.yml b/.github/workflows/tests_allure_test_ops.yml
--- a/.github/workflows/tests_allure_test_ops.yml
+++ b/.github/workflows/tests_allure_test_ops.yml
@@ -103,22 +103,22 @@ jobs:
         run: |
           docker compose up report
 
-      # Шаг 6 - передача отчета в Allure TestOps
-      - name: Send results to Allure TestOps using allurectl
-        run: |               
-          curl -fsSL https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl
-          chmod +x allurectl
-     
-          if [[ ! -f allurectl ]]; then
-            echo "Failed to download allurectl binary."
-            exit 1
-          fi             
-      
-          ./allurectl upload \
-          --endpoint="${{ secrets.ALLURE_TESTOPS_URL }}" \
-          --project-id="${{ secrets.ALLURE_PROJECT_ID }}" \
-          --token="${{ secrets.ALLURE_API_KEY }}" \
-          "./allure-results"
+#      # Шаг 6 - передача отчета в Allure TestOps
+#      - name: Send results to Allure TestOps using allurectl
+#        run: |
+#          curl -fsSL https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -o allurectl
+#          chmod +x allurectl
+#
+#          if [[ ! -f allurectl ]]; then
+#            echo "Failed to download allurectl binary."
+#            exit 1
+#          fi
+#
+#          ./allurectl upload \
+#          --endpoint="${{ secrets.ALLURE_TESTOPS_URL }}" \
+#          --project-id="${{ secrets.ALLURE_PROJECT_ID }}" \
+#          --token="${{ secrets.ALLURE_API_KEY }}" \
+#          "./allure-results"
 
       # Шаг 7 - Деплой на gh-pages, спецальная гитхабовская джоба просто заполняем вот так, заливаем allure-report на ветку gh-pages
       - name: Deploy to Github Pages
